name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: farmville
          POSTGRES_PASSWORD: farmville
          POSTGRES_DB: farmville_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "POSTGRES_USER=farmville" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=farmville" >> $GITHUB_ENV
          echo "POSTGRES_DB=farmville_test" >> $GITHUB_ENV
          echo "JWT_SECRET=test-secret" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=test-key" >> $GITHUB_ENV
          echo "OPENWEATHERMAP_API_KEY=test-key" >> $GITHUB_ENV

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U farmville; do
            sleep 1
          done

      - name: Run tests
        run: make test
